services:
  jira-extractor-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-extractor-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
    volumes:
      - ./output:/app/output
      - ./.env:/app/.env:ro
    restart: unless-stopped
  jira-extractor-scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jira-extractor-scheduler
    command: ["/app/docker/start-scheduler.sh"]
    env_file:
      - .env
    environment:
      TIMEZONE: America/Sao_Paulo
      TZ: America/Sao_Paulo
    volumes:
      - ./output:/app/output
      - ./.env:/app/.env:ro
    restart: unless-stopped
